Repository DeadmanAbir/AgentGenesis, pull requests merged in 2024-11, with the labels that each got.

#102 feat: removing the default action #99
  src/components/react-player.tsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#100 add chatbot integration to website
  .env.sample
  package-lock.json
  package.json
  src/app/(app)/page.tsx
  src/components/chatbot.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#107 Revamp Blog Page UI for Improved User Experience
  public/blog1.svg
  src/app/(app)/blog/blogfinal.tsx
  src/app/(app)/blogs/[postSlug]/page.tsx
  src/app/(app)/blogs/page.tsx
  src/app/(app)/components/[[...slug]]/page.tsx
  src/components/blog-grid.tsx
  src/components/blog.tsx
  src/components/featured-blog-post.tsx
  src/types/blog.ts
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#116 UI: update the blog page #110
  src/components/blog-grid.tsx
  src/components/blog.tsx
  src/components/featured-blog-post.tsx
  src/components/ui/lens.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3
