Repository DeadmanAbir/AgentGenesis, pull requests merged in 2024-10, with the labels that each got.

#45 added blog section by fetching hashnode blogs and rendering with cust…
  package-lock.json
  src/app/(app)/blog/[postSlug]/page.tsx
  src/app/(app)/blog/blogfinal.tsx
  src/app/(app)/blogs/page.tsx
  src/components/Container.tsx
  src/components/Nav.tsx
  src/components/list-blog.tsx
  src/lib/hashnode.ts
  src/lib/pages.tsx
  src/lib/posts.ts
  src/lib/publication.tsx
  src/types/pages.ts
  src/types/posts.ts
  src/types/publication.ts
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#49 fix #43: default tab for linkedin should be playground tab
  src/content/docs/components/linkedinAgent.mdx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#57 Added all contributors in readme
  README.md
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#55 Feature/scrollbar : scroll bar added #53
  src/app/globals.css
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#54 Configured Search For blogs
  .env.sample
  src/components/blog-list-search.tsx
  src/config/doc.ts
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#56 Update Navbar and Routing: Rename 'Docs' to 'Components' and Add 'Contact Us'
  contentlayer.config.ts
  package.json
  src/app/(app)/components/[[...slug]]/page.tsx
  src/app/(app)/components/layout.tsx
  src/components/features.tsx
  src/components/main-nav.tsx
  src/config/doc.ts
  src/content/components/calculatorTool.mdx
  src/content/components/chatAnthropic.mdx
  src/content/components/chatGemini.mdx
  src/content/components/chatOpenAi.mdx
  src/content/components/cohereReranker.mdx
  src/content/components/geminiEmbedding.mdx
  src/content/components/index.mdx
  src/content/components/linkedinAgent.mdx
  src/content/components/linkedinTool.mdx
  src/content/components/openAiEmbedding.mdx
  src/content/components/searchapiTool.mdx
  src/content/components/unstructuredLoader.mdx
  src/content/components/wikipediaTool.mdx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#47 fixes #44: Adds Rate limiting to linkedIn agent Playground
  .env.sample
  package-lock.json
  package.json
  src/app/api/agent/core.ts
  src/app/api/agent/route.ts
  src/components/DemoComponents/LinkedinAgent.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#65 Added PR Validator Workflow
  .github/workflows/PRValidator.yml
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#79 Done The Enhancements
  CONTRIBUTING.md
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#87 Added Table to Display Repository Statistics in README.md
  README.md
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#89 update sidebar w/o blog tab
  package-lock.json
  src/components/command-menu.tsx
  src/components/sidebar-nav.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level 2
